name: Deploy React

on:
  push:
    branches: [ "main", "deploy" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .env
        run: |
          echo "${{ secrets.DOT_ENV }}" > .env
      
      - uses: actions/setup-node@v4
      - run: npm install axios

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          # 서버에 파일만 배포
          source: dist/*
          target: ~/deploy